"""Add role field to User

Revision ID: f08c51acc35c
Revises: 
Create Date: 2025-04-06 19:42:10.852603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f08c51acc35c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum type userrole if it doesn't already exist
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'userrole') THEN
            CREATE TYPE userrole AS ENUM ('admin', 'user', 'designer');
        END IF;
    END
    $$;
    """)

    # Alter the 'role' column and cast existing data to 'userrole' type
    op.execute(
        'ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole')

    # Alter column to make it non-nullable (if necessary)
    op.alter_column('users', 'role',
                    existing_type=postgresql.ENUM(
                        'admin', 'user', 'designer', name='user_role'),
                    type_=sa.Enum('admin', 'user', 'designer',
                                  name='userrole'),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Change column type back to old enum type 'user_role'
    op.execute(
        'ALTER TABLE users ALTER COLUMN role TYPE user_role USING role::user_role')

    # Drop the 'userrole' type if no longer used
    op.execute('DROP TYPE userrole')

    # Alter column to make it nullable again (if necessary)
    op.alter_column('users', 'role',
                    existing_type=sa.Enum(
                        'admin', 'user', 'designer', name='userrole'),
                    type_=postgresql.ENUM(
                        'admin', 'user', 'designer', name='user_role'),
                    nullable=True)
    # ### end Alembic commands ###
